// @generated

// These modules are generated by build.rs using ttrpc_codegen
pub mod attestation_agent;        // Contains the protobuf message structures
pub mod attestation_agent_ttrpc;  // Contains the ttrpc client and server definitions
